name: Deploy Workflow
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Deploy
    strategy:
      matrix:
        node-version: [10]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v1
      - run: node --version
      - run: npm install
      - run: npm install --only=dev
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
